spring:
  application:
    name: CloudFileSystem
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_file_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 274581@friX
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8835
jwt:
  secret: CloudFileSystemDefaultSecretKeyForJWT2026MinimumLength64CharactersRequired
  default-expiration: 604800